
// ===================== VYNK PRODUCT DATA =====================
// Edit product names, prices, descriptions, images and customization here.
// Prices are in PKR. Image URLs can be replaced with local assets such as assets/images/standee.webp.
const PRODUCTS = [
 {id:"standee-pro",category:"nfc-standee",name:"VYNK NFC Smart Standee",price:2499,image:"https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1000&q=85",description:"A premium NFC standee designed for instant profile sharing, reviews, links and contact details.",features:["Tap-to-share NFC","Premium display design","Easy setup","Reusable digital destination"],customization:["Black","Gold"]},
 {id:"standee-review",category:"nfc-standee",name:"NFC Review Standee",price:1999,image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85",description:"Turn every customer interaction into a fast review opportunity with one simple tap.",features:["Google review focused","Tap-and-go experience","Countertop friendly","Branded presentation"],customization:["Black","White"]},
 {id:"card-metal",category:"nfc-cards",name:"VYNK Metal NFC Card",price:2999,image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=85",description:"A sleek NFC business card built for modern professionals who want a premium first impression.",features:["NFC enabled","QR backup","Digital profile ready","Premium metal finish"],customization:["Matte Black","Brushed Gold"]},
 {id:"card-pvc",category:"nfc-cards",name:"VYNK Premium NFC Card",price:1499,image:"https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1000&q=85",description:"Minimal, durable and easy to carry. Share your digital business identity with a tap.",features:["Lightweight PVC","NFC enabled","Custom branding","QR backup"],customization:["Black","White","Gold"]},
 {id:"review-plate",category:"google-review-products",name:"Google Review Tap Plate",price:1299,image:"https://images.unsplash.com/photo-1556742111-a301076d9d18?auto=format&fit=crop&w=1000&q=85",description:"A compact branded review plate that makes requesting Google reviews effortless.",features:["NFC tap","QR code","Custom branding","Counter or wall use"],customization:["Black","White"]},
 {id:"review-card",category:"google-review-products",name:"Google Review NFC Card",price:999,image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=85",description:"A simple NFC review card for teams, shops, salons, restaurants and service businesses.",features:["Tap to review","QR backup","Custom logo","Portable"],customization:["Black","White"]},
 {id:"profile-starter",category:"digital-business-profiles",name:"VYNK Digital Profile — Starter",price:2499,image:"https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1000&q=85",description:"A polished digital business profile with your essential links, contact information and social presence.",features:["Mobile profile","Contact buttons","Social links","Shareable URL"],customization:["Business","Personal"]},
 {id:"profile-pro",category:"digital-business-profiles",name:"VYNK Digital Profile — Pro",price:4999,image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85",description:"An elevated digital identity for professionals and brands that need a stronger online presence.",features:["Premium profile","Lead/contact buttons","Social links","Custom branding","Analytics-ready structure"],customization:["Business","Creator","Professional"]}
];

const CATEGORIES = {
 "nfc-standee":{title:"NFC Standee",desc:"Premium tap-to-share standees for businesses, creators and customer experiences.",banner:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1800&q=85"},
 "nfc-cards":{title:"NFC Cards",desc:"Modern NFC business cards designed to replace paper with a smarter digital identity.",banner:"https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1800&q=85"},
 "google-review-products":{title:"Google Review Products",desc:"Make it effortless for customers to discover and leave your business a review.",banner:"https://images.unsplash.com/photo-1556742111-a301076d9d18?auto=format&fit=crop&w=1800&q=85"},
 "digital-business-profiles":{title:"Digital Business Profiles",desc:"Professional digital profiles that keep your business identity one tap away.",banner:"https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1800&q=85"}
};
const WA="923392101633";

function money(n){return "PKR "+Number(n).toLocaleString("en-PK")}
function getCart(){return JSON.parse(localStorage.getItem("vynk_cart")||"[]")}
function setCart(c){localStorage.setItem("vynk_cart",JSON.stringify(c));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=n)}
function qs(k){return new URLSearchParams(location.search).get(k)}
function productCard(p){return `<article class="card"><a href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.name}"></a><div class="cardbody"><h3>${p.name}</h3><div class="cardrow"><span class="price">${money(p.price)}</span><a class="smallbtn" href="product.html?id=${p.id}">View Product</a></div></div></article>`}
function header(){
return `<div class="announce">Premium NFC & Digital Business Solutions — Designed for modern brands</div>
<header class="header"><nav class="nav"><a class="logo" href="index.html">V<span>Y</span>NK</a>
<div class="navlinks"><a href="index.html">Home</a><a href="category.html?cat=nfc-standee">NFC Standee</a><a href="category.html?cat=nfc-cards">NFC Cards</a><a href="category.html?cat=google-review-products">Reviews</a><a href="category.html?cat=digital-business-profiles">Profiles</a><a href="contact.html">Contact</a></div>
<div class="actions"><button class="iconbtn mobile-toggle" onclick="toggleMenu()" aria-label="Menu">☰</button><button class="iconbtn" onclick="searchPrompt()" aria-label="Search">⌕</button><a class="iconbtn" href="cart.html" aria-label="Cart">🛒<sup data-cart-count>0</sup></a></div></nav></header>`}
function footer(){return `<footer class="footer"><div class="footerin"><div><div class="logo">V<span>Y</span>NK</div><p>Custom NFC products and digital business solutions built to make every interaction smarter.</p></div><div><h4>Shop</h4><a href="category.html?cat=nfc-standee">NFC Standee</a><a href="category.html?cat=nfc-cards">NFC Cards</a><a href="category.html?cat=google-review-products">Google Review Products</a></div><div><h4>Solutions</h4><a href="category.html?cat=digital-business-profiles">Digital Profiles</a><a href="contact.html">Contact Us</a><a href="cart.html">Cart</a></div><div><h4>WhatsApp</h4><p>+92 339 2101633</p><a href="https://wa.me/${WA}" target="_blank" rel="noopener">Chat on WhatsApp →</a></div></div></footer>`}
function searchPrompt(){const q=prompt("Search VYNK products"); if(q) location.href="index.html?search="+encodeURIComponent(q)}
function toggleMenu(){alert("On smaller screens, use the category links available from the homepage and product pages.")}
function layout(content){document.getElementById("site").innerHTML=header();document.getElementById("app").innerHTML=content+footer();updateCartCount()}
function home(){
const featured=PRODUCTS.slice(0,4), best=PRODUCTS.slice(2,6), fresh=PRODUCTS.slice(4,8);
const cats=Object.entries(CATEGORIES).map(([k,v])=>`<a class="cat" href="category.html?cat=${k}" style="background-image:url('${v.banner}')"><div><h3>${v.title}</h3><p>Explore collection →</p></div></a>`).join("");
let search=qs("search"), shown=PRODUCTS; if(search) shown=PRODUCTS.filter(p=>(p.name+" "+p.description).toLowerCase().includes(search.toLowerCase()));
layout(`<section class="hero"><div class="hero-inner"><div class="eyebrow">VYNK / Digital First</div><h1>Make every interaction feel premium.</h1><p>Smart NFC products and digital business solutions crafted for brands that want a faster, cleaner, more memorable way to connect.</p><a class="btn" href="category.html?cat=nfc-standee">Shop Now</a></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Curated for you</div><h2>${search?`Search results for “${search}”`:"Featured Products"}</h2></div></div><div class="grid">${(search?shown:featured).map(productCard).join("")}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Explore VYNK</div><h2>Shop by Category</h2></div></div><div class="categories">${cats}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Customer favourites</div><h2>Best Sellers</h2></div></div><div class="grid">${best.map(productCard).join("")}</div></section>
<section class="intro"><div class="section"><div><div class="eyebrow">The VYNK Standard</div><h2>From a tap to a lasting impression.</h2></div><div><p>VYNK brings physical and digital experiences together. Give customers a simple tap, a polished profile and a faster path to your business.</p><a class="btn alt" href="contact.html">Talk to VYNK</a></div></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Fresh drops</div><h2>New Arrivals</h2></div></div><div class="grid">${fresh.map(productCard).join("")}</div></section>`);
}
function category(){
const c=CATEGORIES[qs("cat")]||CATEGORIES["nfc-standee"]; const items=PRODUCTS.filter(p=>p.category===qs("cat"));
layout(`<section class="pagehero" style="background:linear-gradient(90deg,rgba(0,0,0,.9),rgba(0,0,0,.3)),url('${c.banner}') center/cover"><div class="inner"><div class="crumb"><a href="index.html">Home</a> / ${c.title}</div><h1>${c.title}</h1><p class="muted">${c.desc}</p></div></section><section class="section"><div class="grid">${items.map(productCard).join("")}</div></section>`);
}
function product(){
const p=PRODUCTS.find(x=>x.id===qs("id"))||PRODUCTS[0];
const related=PRODUCTS.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,4);
layout(`<section class="section"><div class="crumb"><a href="index.html">Home</a> / <a href="category.html?cat=${p.category}">${CATEGORIES[p.category].title}</a> / ${p.name}</div><br><div class="product"><div><img src="${p.image}" alt="${p.name}"></div><div><div class="eyebrow">${CATEGORIES[p.category].title}</div><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="muted">${p.description}</p><div>${p.features.map(f=>`<div class="feature">✓ ${f}</div>`).join("")}</div><div class="controls">${p.customization?.length?`<label>Customization<select id="custom">${p.customization.map(x=>`<option>${x}</option>`).join("")}</select></label>`:""}<label>Quantity<div class="qty"><button onclick="changeQty(-1)">−</button><input id="qty" type="number" value="1" min="1"><button onclick="changeQty(1)">+</button></div></label></div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" onclick="buyNow('${p.id}')">Buy Now on WhatsApp</button><button class="btn alt" onclick="addToCart('${p.id}')">Add to Cart</button></div></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">You may also like</div><h2>Related Products</h2></div></div><div class="grid">${related.map(productCard).join("")}</div></section>`);
}
function changeQty(d){const i=document.getElementById("qty");i.value=Math.max(1,Number(i.value)+d)}
function customization(){const e=document.getElementById("custom");return e?e.value:"None"}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id), qty=Math.max(1,Number(document.getElementById("qty")?.value||1)), custom=customization();let c=getCart(), found=c.find(x=>x.id===id&&x.custom===custom);if(found)found.qty+=qty;else c.push({id,qty,custom});setCart(c);alert("Added to cart.")}
function waMessage(items){return "Hi VYNK! I want to order "+items.map(x=>`${x.name}. Quantity: ${x.qty}. Customization: ${x.custom||"None"}.`).join(" ")+" Please share the payment and delivery details."}
function buyNow(id){const p=PRODUCTS.find(x=>x.id===id),qty=Math.max(1,Number(document.getElementById("qty")?.value||1));window.open("https://wa.me/"+WA+"?text="+encodeURIComponent(waMessage([{...p,qty,custom:customization()}])),"_blank")}
function cart(){
const c=getCart(); const rows=c.map((x,i)=>{const p=PRODUCTS.find(p=>p.id===x.id);return `<div class="cartitem"><img src="${p.image}" alt="${p.name}"><div><strong>${p.name}</strong><div class="muted">${money(p.price)} · ${x.custom}</div><div class="qty"><button onclick="cartQty(${i},-1)">−</button><span>${x.qty}</span><button onclick="cartQty(${i},1)">+</button></div></div><div><strong>${money(p.price*x.qty)}</strong><br><button class="smallbtn" onclick="removeCart(${i})">Remove</button></div></div>`}).join("");
const subtotal=c.reduce((s,x)=>s+(PRODUCTS.find(p=>p.id===x.id).price*x.qty),0);
layout(`<section class="pagehero"><div class="inner"><div class="crumb"><a href="index.html">Home</a> / Cart</div><h1>Your Cart</h1><p class="muted">Review your items before ordering on WhatsApp.</p></div></section><section class="section">${c.length?`${rows}<div class="carttotal"><span>Subtotal</span><span class="price">${money(subtotal)}</span></div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn alt" href="index.html">Continue Shopping</a><button class="btn" onclick="checkoutCart()">Proceed to WhatsApp</button></div>`:`<div class="empty">Your cart is empty.<br><br><a class="btn" href="index.html">Shop VYNK</a></div>`}</section>`);
}
function cartQty(i,d){let c=getCart();c[i].qty=Math.max(1,c[i].qty+d);setCart(c);cart()}
function removeCart(i){let c=getCart();c.splice(i,1);setCart(c);cart()}
function checkoutCart(){const c=getCart();const items=c.map(x=>({...PRODUCTS.find(p=>p.id===x.id),qty:x.qty,custom:x.custom}));window.open("https://wa.me/"+WA+"?text="+encodeURIComponent(waMessage(items)),"_blank")}
function contact(){
layout(`<section class="pagehero"><div class="inner"><div class="crumb"><a href="index.html">Home</a> / Contact</div><h1>Contact VYNK</h1><p class="muted">Let's build a smarter customer experience for your brand.</p></div></section><section class="section"><div class="contact"><div><div class="eyebrow">WhatsApp</div><h2>+92 339 2101633</h2><p class="muted">For product orders, customization and delivery details.</p><a class="btn" href="https://wa.me/${WA}" target="_blank" rel="noopener">Chat on WhatsApp</a><div class="notice" style="margin-top:22px">WhatsApp ordering is available immediately. The contact form below is a static front-end form until connected to a backend/form service.</div></div><form onsubmit="submitContact(event)"><input required placeholder="Name"><input required type="email" placeholder="Email"><textarea required placeholder="Message"></textarea><button class="btn" type="submit">Send Message</button><div id="formmsg" class="muted"></div></form></div></section>`);
}
function submitContact(e){e.preventDefault();document.getElementById("formmsg").textContent="Thanks — your message is ready to be connected to a form backend."}
document.addEventListener("DOMContentLoaded",()=>{const page=document.body.dataset.page;if(page==="home")home();if(page==="category")category();if(page==="product")product();if(page==="cart")cart();if(page==="contact")contact()});
